name: quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - cvxpy
  - cvxopt
#  - alphalens
  - empyrical
#  - pyfolio
#  - pyportfolioopt
#  - riskfolio-lib
#  - mlfinlab
  - tqdm
  - jupyterlab
  - pip
  - ipython
